name = "aetherways-api-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-24"

[vars]
# For local testing, use: http://localhost:5173
# For production, use: https://asmithcodes.github.io
ALLOWED_ORIGIN = "http://localhost:3000"
